# Generated by Django 5.0.2 on 2026-01-31 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('background_color', models.CharField(default='#f9fafb', max_length=20)),
                ('font_color', models.CharField(default='#000000', max_length=20)),
                ('header_color', models.CharField(default='#7c3aed', max_length=20)),
                ('accent_color', models.CharField(default='#10b981', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customizations',
            },
        ),
    ]
