# Generated by Django 5.0.2 on 2026-02-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='price_type',
            field=models.CharField(choices=[('portion', 'Portion Prices (Full/Half/Quarter)'), ('combo', 'Combo Price'), ('single', 'Single Price')], default='single', max_length=10),
        ),
    ]
