# Generated by Django 5.0.2 on 2026-02-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_menuitem_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='header_bg_color',
            field=models.CharField(blank=True, default='#6366f1', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customization',
            name='header_text_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customization',
            name='primary_color',
            field=models.CharField(blank=True, default='#7c3aed', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customization',
            name='qr_background_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customization',
            name='qr_foreground_color',
            field=models.CharField(blank=True, default='#000000', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customization',
            name='qr_margin',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AddField(
            model_name='customization',
            name='qr_size',
            field=models.IntegerField(blank=True, default=512, null=True),
        ),
    ]
