# Generated by Django 5.0.2 on 2026-02-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customization_header_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='logo_shape',
            field=models.CharField(blank=True, default='round', max_length=20, null=True),
        ),
    ]
