# Generated by Django 5.0.2 on 2026-02-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customization_logo_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='phone2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='pin_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
