# Generated by Django 5.0.2 on 2026-02-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_companyinfo_district_companyinfo_phone2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='waiter_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
