# Generated by Django 6.0 on 2026-02-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_order_waiter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='role',
            field=models.CharField(blank=True, choices=[('waiter', 'Waiter'), ('kitchen', 'Kitchen'), ('both', 'Both')], default=None, help_text="Panel access role — only used for staff (user_type='user')", max_length=10, null=True),
        ),
    ]
