# Generated by Django 5.0.2 on 2026-02-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_appuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='member_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of guests at the table'),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=100)),
                ('username', models.CharField(db_index=True, max_length=100)),
                ('table_number', models.CharField(max_length=50)),
                ('table_name', models.CharField(blank=True, help_text="Optional descriptive label, e.g. 'Window Seat' or 'VIP Room'", max_length=100, null=True)),
                ('capacity', models.PositiveIntegerField(default=4, help_text='Maximum number of guests')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tables',
                'ordering': ['table_number'],
                'indexes': [models.Index(fields=['client_id', 'username', 'status'], name='tables_client__6d3491_idx')],
                'unique_together': {('username', 'table_number')},
            },
        ),
    ]
