# Generated by Django 6.0 on 2026-02-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_order_customer_phone_order_member_count_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=100)),
                ('username', models.CharField(db_index=True, max_length=100)),
                ('image', models.ImageField(upload_to='tv_banners/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TV Banner',
                'verbose_name_plural': 'TV Banners',
                'db_table': 'tv_banners',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['client_id', 'username', 'is_active'], name='tv_banners_client__a36c4b_idx')],
            },
        ),
    ]
