# Generated by Django 6.0 on 2026-02-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_tvbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='tv_bg_color',
            field=models.CharField(blank=True, default='#000000', help_text='Background color of the TV Menu Display screen', max_length=20, null=True),
        ),
    ]
