# Generated by Django 6.0 on 2026-02-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_customization_tv_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='tv_accent_color',
            field=models.CharField(blank=True, default='#9333ea', help_text='Accent/highlight color on the TV Menu Display screen', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customization',
            name='tv_card_bg_color',
            field=models.CharField(blank=True, default='#1f2937', help_text='Card background color on the TV Menu Display screen', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customization',
            name='tv_text_color',
            field=models.CharField(blank=True, default='#ffffff', help_text='Text color on the TV Menu Display screen', max_length=20, null=True),
        ),
    ]
