# Generated by Django 6.0 on 2026-02-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_customization_tv_accent_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customization',
            name='tv_accent_color',
        ),
        migrations.RemoveField(
            model_name='customization',
            name='tv_card_bg_color',
        ),
        migrations.RemoveField(
            model_name='customization',
            name='tv_text_color',
        ),
        migrations.AddField(
            model_name='customization',
            name='tv_logo',
            field=models.ImageField(blank=True, help_text='Logo shown in the TV Menu Display header', null=True, upload_to='tv_logos/'),
        ),
    ]
