# Generated by Django 6.0 on 2026-02-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_customization_tv_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='tv_accent_color',
            field=models.CharField(blank=True, default='#9333ea', help_text='Accent/highlight color for the TV Menu Display screen', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customization',
            name='tv_card_bg_color',
            field=models.CharField(blank=True, default='#1f2937', help_text='Card background color for the TV Menu Display screen', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customization',
            name='tv_text_color',
            field=models.CharField(blank=True, default='#ffffff', help_text='Text color for the TV Menu Display screen', max_length=20, null=True),
        ),
    ]
