# Generated by Django 6.0 on 2026-03-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_customization_tv_accent_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='leasing_key',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
