# Generated by Django 5.0.2 on 2026-03-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_companyinfo_leasing_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='allowed_pages',
            field=models.JSONField(blank=True, default=None, help_text='List of page IDs accessible to this company. NULL = unrestricted.', null=True),
        ),
    ]
