# Generated by Django 5.0.2 on 2026-03-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_companyinfo_allowed_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='allowed_pages',
            field=models.JSONField(blank=True, default=None, help_text='List of page IDs this staff user can access. NULL = not configured.', null=True),
        ),
    ]
