# Generated by Django 6.0 on 2026-03-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_appuser_allowed_pages'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='category',
            name='client_id',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('client_id', 'name')},
        ),
    ]
