# Generated by Django 5.0.2 on 2026-03-17 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_category_add_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='plain_password',
            field=models.CharField(blank=True, help_text='Stored in plain text for Super Admin visibility only.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='plain_password',
            field=models.CharField(blank=True, help_text='Stored in plain text for Super Admin visibility only.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tvbanner',
            name='plain_password',
            field=models.CharField(blank=True, help_text='Stored in plain text for Super Admin visibility only.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='allowed_pages',
            field=models.JSONField(blank=True, default=None, help_text='Pages this staff user can access. NULL = not set.', null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='company',
            field=models.ForeignKey(blank=True, db_column='client_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.companyinfo'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(blank=True, choices=[('waiter', 'Waiter'), ('kitchen', 'Kitchen'), ('both', 'Both')], default=None, help_text="Only for staff (user_type='user')", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user_type',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Company Admin'), ('user', 'Staff')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='allowed_pages',
            field=models.JSONField(blank=True, default=None, help_text='Page IDs this company can access. NULL = unrestricted.', null=True),
        ),
        migrations.AlterField(
            model_name='customization',
            name='tv_accent_color',
            field=models.CharField(blank=True, default='#9333ea', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customization',
            name='tv_bg_color',
            field=models.CharField(blank=True, default='#000000', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customization',
            name='tv_card_bg_color',
            field=models.CharField(blank=True, default='#1f2937', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customization',
            name='tv_logo',
            field=models.ImageField(blank=True, null=True, upload_to='tv_logos/'),
        ),
        migrations.AlterField(
            model_name='customization',
            name='tv_text_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price_type',
            field=models.CharField(choices=[('portion', 'Portion Prices'), ('combo', 'Combo Price'), ('single', 'Single Price')], default='single', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='member_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
