# Generated by Django 5.0.2 on 2026-03-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_appuser_plain_password_banner_plain_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='package',
            field=models.CharField(choices=[('premium', 'Premium'), ('pro', 'Pro'), ('basic', 'Basic')], default='premium', help_text='Subscription plan: premium=all pages, pro=core only, basic=core+staff+waiter', max_length=20),
        ),
    ]
