# Generated by Django 5.0.2 on 2026-03-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_social_links_to_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='food_type',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('egg', 'Egg')], default='non_veg', help_text='Veg / Non-Veg / Egg indicator for the menu item.', max_length=10),
        ),
    ]
