# Generated by Django 5.0.2 on 2026-03-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_menuitem_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='food_type',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian')], default='non_veg', help_text='Veg / Non-Veg indicator for the menu item.', max_length=10),
        ),
    ]
