# Generated by Django 6.0 on 2026-03-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_add_food_type_to_menuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='role',
        ),
        migrations.AddField(
            model_name='appuser',
            name='staff_role',
            field=models.CharField(blank=True, choices=[('waiter', 'Waiter'), ('kitchen', 'Kitchen'), ('both', 'Both')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='meal_type',
            field=models.CharField(choices=[('all', 'All Day'), ('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default='all', help_text='Breakfast / Lunch / Dinner / All Day. Used for time-based menu filtering.', max_length=10),
        ),
    ]
