# Generated by Django 6.0 on 2026-03-28 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_appuser_role_appuser_staff_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='staff_role',
        ),
        migrations.AddField(
            model_name='appuser',
            name='role',
            field=models.CharField(blank=True, help_text="Staff role: 'waiter', 'kitchen', or 'both'.", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='company',
            field=models.ForeignKey(blank=True, help_text='NULL only for superadmin accounts.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.companyinfo'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='meal_type',
            field=models.CharField(blank=True, default='', help_text='ID of the MealType row. Empty = shown all day.', max_length=20),
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField(help_text='Meal period start time, e.g. 07:00')),
                ('end_time', models.TimeField(help_text='Meal period end time, e.g. 11:00')),
                ('client_id', models.CharField(db_index=True, max_length=100)),
                ('username', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meal Type',
                'verbose_name_plural': 'Meal Types',
                'db_table': 'meal_types',
                'ordering': ['start_time', 'name'],
                'indexes': [models.Index(fields=['client_id', 'username'], name='meal_types_client__301b0e_idx')],
                'unique_together': {('client_id', 'name')},
            },
        ),
    ]
