# Generated by Django 6.0 on 2026-03-30 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_menuitem_meal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen_number', models.CharField(max_length=50)),
                ('kitchen_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('client_id', models.CharField(db_index=True, max_length=100)),
                ('username', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kitchen',
                'verbose_name_plural': 'Kitchens',
                'db_table': 'kitchens',
                'ordering': ['kitchen_number'],
                'indexes': [models.Index(fields=['client_id', 'username', 'status'], name='kitchens_client__86d188_idx')],
                'unique_together': {('username', 'kitchen_number')},
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='kitchen',
            field=models.ForeignKey(blank=True, help_text='Kitchen that prepares this item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='api.kitchen'),
        ),
    ]
