# Generated by Django 6.0 on 2026-03-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_kitchen_menuitem_kitchen'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='kitchen',
            name='kitchens_client__86d188_idx',
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='kitchen_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='kitchen',
            index=models.Index(fields=['client_id', 'username'], name='kitchens_client__e941da_idx'),
        ),
        migrations.RemoveField(
            model_name='kitchen',
            name='description',
        ),
        migrations.RemoveField(
            model_name='kitchen',
            name='status',
        ),
    ]
