# Generated by Django 6.0 on 2026-04-03 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_kitchen_kitchens_client__86d188_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customization',
            name='tv_theme',
            field=models.CharField(blank=True, choices=[('theme1', 'Dark Card Grid'), ('theme2', 'Cinematic Fullscreen'), ('theme3', 'Elegant Warm Split')], default='theme1', help_text='Which TV display layout/theme to use on the MenuDisplay screen.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='allowed_pages',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.companyinfo'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(blank=True, choices=[('waiter', 'Waiter'), ('cashier', 'Cashier'), ('both', 'Both')], default='both', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='client_id',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='kitchen',
            field=models.ForeignKey(blank=True, help_text='Kitchen assigned to prepare this item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='api.kitchen'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='meal_type',
            field=models.JSONField(blank=True, default=list, help_text='List of MealType IDs this item is available for. Empty = all day.', null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterModelTable(
            name='menuitem',
            table='menu_items',
        ),
    ]
