# Generated by Django 6.0 on 2026-04-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_menuitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvbanner',
            name='image',
            field=models.FileField(upload_to='tv_banners/'),
        ),
    ]
