# Generated by Django 6.0 on 2026-04-06 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_tvbanner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='price_category',
            field=models.CharField(choices=[('regular', 'Regular Price'), ('sessional', 'Sessional Price')], default='regular', help_text='Whether this item uses a regular fixed price or sessional pricing.', max_length=10),
        ),
        migrations.CreateModel(
            name='SessionalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(help_text='Label for this price session, e.g. "Breakfast", "Happy Hour".', max_length=100)),
                ('price1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(help_text='The menu item this sessional price belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='sessional_prices', to='api.menuitem')),
            ],
            options={
                'verbose_name': 'Sessional Price',
                'verbose_name_plural': 'Sessional Prices',
                'db_table': 'sessional_prices',
                'ordering': ['session_name'],
                'unique_together': {('menu_item', 'session_name')},
            },
        ),
    ]
