# Generated by Django 6.0 on 2026-04-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_menuitem_price_category_sessionalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='tv_theme2_left',
            field=models.FileField(blank=True, null=True, upload_to='tv_theme2/'),
        ),
        migrations.AddField(
            model_name='customization',
            name='tv_theme2_right',
            field=models.FileField(blank=True, null=True, upload_to='tv_theme2/'),
        ),
        migrations.AddField(
            model_name='customization',
            name='tv_theme3_image',
            field=models.ImageField(blank=True, null=True, upload_to='tv_theme3/'),
        ),
        migrations.AddField(
            model_name='customization',
            name='tv_theme3_video',
            field=models.FileField(blank=True, null=True, upload_to='tv_theme3/'),
        ),
    ]
