# Generated by Django 6.0 on 2026-04-11 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_customization_tv_theme2_left_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sessionalprice',
            options={'ordering': ['session_name']},
        ),
        migrations.AlterUniqueTogether(
            name='sessionalprice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='table',
            name='occupied_seats',
            field=models.PositiveIntegerField(default=0, help_text='Current number of occupied seats. Auto-managed by order lifecycle.'),
        ),
        migrations.AddField(
            model_name='table',
            name='table_type',
            field=models.CharField(choices=[('sharing', 'Sharing'), ('sitting', 'Sitting / Fixed')], default='sitting', help_text='sitting = the whole table is booked as one unit; sharing = multiple independent groups can occupy spare seats.', max_length=10),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(blank=True, help_text='Staff role: waiter | cashier | both', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customization',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
        migrations.AlterField(
            model_name='customization',
            name='font_color',
            field=models.CharField(default='#1f2937', max_length=20),
        ),
        migrations.AlterField(
            model_name='customization',
            name='tv_theme',
            field=models.CharField(blank=True, choices=[('theme1', 'Theme 1 — Classic'), ('theme2', 'Theme 2 — Split Panel'), ('theme3', 'Theme 3 — Media Banner')], default='theme1', help_text='Which TV display layout/theme to use on the MenuDisplay screen.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='kitchen',
            field=models.ForeignKey(blank=True, help_text='Which kitchen prepares this item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='api.kitchen'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='meal_type',
            field=models.JSONField(blank=True, default=list, help_text='List of MealType IDs (strings) this item belongs to.', null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price_category',
            field=models.CharField(choices=[('regular', 'Regular Price'), ('sessional', 'Sessional Price')], default='regular', help_text='Regular price or Sessional (time-based) price.', max_length=10),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='api.tax'),
        ),
        migrations.AlterField(
            model_name='sessionalprice',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessional_prices', to='api.menuitem'),
        ),
        migrations.AlterField(
            model_name='sessionalprice',
            name='session_name',
            field=models.CharField(help_text='e.g. Breakfast, Lunch, Dinner', max_length=100),
        ),
        migrations.AddIndex(
            model_name='appuser',
            index=models.Index(fields=['username'], name='app_users_usernam_670fd3_idx'),
        ),
        migrations.AddIndex(
            model_name='appuser',
            index=models.Index(fields=['user_type', 'is_active'], name='app_users_user_ty_175942_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['client_id', 'username', 'status'], name='menu_items_client__34abfa_idx'),
        ),
    ]
