# Generated by Django 6.0 on 2026-04-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_appuser_options_alter_sessionalprice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('billing_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('client_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('table_number', models.CharField(blank=True, max_length=50, null=True)),
                ('table_name', models.CharField(blank=True, max_length=200, null=True)),
                ('items', models.JSONField(blank=True, default=list, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'billing_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
