# Generated by Django 6.0 on 2026-04-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_billingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('self', 'Self Order (QR)'), ('staff', 'Staff Order')], db_index=True, default='self', help_text='"self" = customer QR order that requires waiter acceptance; "staff" = direct staff order with instant billing.', max_length=10),
        ),
    ]
