# Generated by Django 6.0 on 2026-04-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='tv_grid_columns',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='customization',
            name='tv_items_per_page',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
    ]
