# Generated by Django 6.0 on 2026-04-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_customization_tv_grid_columns_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=100)),
                ('username', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_bills', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('upi_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('card_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_bills', models.IntegerField(default=0)),
                ('upi_bills', models.IntegerField(default=0)),
                ('card_bills', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sale_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.RemoveField(
            model_name='customization',
            name='tv_grid_columns',
        ),
        migrations.RemoveField(
            model_name='customization',
            name='tv_items_per_page',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='price_category',
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card')], default='cash', max_length=20),
        ),
        migrations.DeleteModel(
            name='SessionalPrice',
        ),
    ]
