# Generated by Django 6.0 on 2026-04-25 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_salesession_remove_customization_tv_grid_columns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='sale_session',
            field=models.ForeignKey(blank=True, help_text='The sale session this bill belongs to. Set automatically on save_billing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_records', to='api.salesession'),
        ),
    ]
