# Generated by Django 6.0 on 2026-04-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_billingrecord_sale_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='order_type',
            field=models.CharField(blank=True, choices=[('dine_in', 'Dine In'), ('delivery', 'Delivery'), ('takeaway', 'Takeaway')], default='dine_in', help_text='"dine_in" = table order, "delivery" = delivery order, "takeaway" = takeaway order.', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('self', 'Self Order (QR)'), ('staff', 'Staff Order'), ('delivery', 'Delivery'), ('takeaway', 'Takeaway')], db_index=True, default='self', help_text='"self" = customer QR order that requires waiter acceptance; "staff" = direct staff order with instant billing; "delivery" = delivery order; "takeaway" = takeaway order.', max_length=10),
        ),
    ]
