# Generated by Django 6.0 on 2026-04-30 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_billingrecord_order_type_alter_order_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=100)),
                ('username', models.CharField(db_index=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, help_text='Current remaining quantity.', max_digits=10)),
                ('unit', models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilograms'), ('g', 'Grams'), ('L', 'Litres'), ('mL', 'Millilitres'), ('plate', 'Plate'), ('bowl', 'Bowl'), ('dozen', 'Dozen'), ('box', 'Box'), ('pack', 'Pack')], default='pcs', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(help_text='The menu item this stock row tracks.', on_delete=django.db.models.deletion.CASCADE, related_name='stock_item', to='api.menuitem')),
            ],
            options={
                'verbose_name': 'Stock Item',
                'verbose_name_plural': 'Stock Items',
                'db_table': 'stock_items',
                'ordering': ['menu_item__category__name', 'menu_item__name'],
                'indexes': [models.Index(fields=['client_id', 'username'], name='stock_items_client__8639c3_idx')],
                'unique_together': {('client_id', 'menu_item')},
            },
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=100)),
                ('username', models.CharField(db_index=True, max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=200)),
                ('category_name', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(choices=[('add', 'Add'), ('deduct', 'Deduct'), ('adjust', 'Adjust')], default='add', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='pcs', max_length=10)),
                ('prev_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('date', models.DateField(help_text='Business date of the movement (supplied by client).')),
                ('billing_id', models.CharField(blank=True, help_text='Billing reference if this was a billing-triggered deduction.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_logs', to='api.menuitem')),
            ],
            options={
                'verbose_name': 'Stock Log',
                'verbose_name_plural': 'Stock Logs',
                'db_table': 'stock_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client_id', 'username', '-created_at'], name='stock_logs_client__65d97a_idx'), models.Index(fields=['client_id', 'type'], name='stock_logs_client__6f6968_idx')],
            },
        ),
    ]
