# Generated by Django 6.0 on 2026-05-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_stockitem_stocklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineSyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text='API path, e.g. /api/orders/', max_length=500)),
                ('method', models.CharField(choices=[('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10)),
                ('payload', models.JSONField(default=dict, help_text='JSON body of the original request')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('error_msg', models.TextField(blank=True)),
                ('retries', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Offline Sync Queue',
                'verbose_name_plural': 'Offline Sync Queue',
                'db_table': 'offline_sync_queue',
                'ordering': ['created_at'],
            },
        ),
    ]
