# Generated by Django 6.0 on 2026-05-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_offlinesyncqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingrecord',
            name='order_type',
            field=models.CharField(blank=True, choices=[('dine_in', 'Dine In'), ('delivery', 'Delivery'), ('takeaway', 'Takeaway'), ('staff', 'Staff Order')], default='dine_in', help_text='"dine_in" = table/QR order, "staff" = staff-placed table order, "delivery"/"takeaway" = off-table orders.', max_length=10),
        ),
    ]
